(deftheme my-misterioso
  "Predominantly blue/cyan faces on a dark cyan background. Background is darker than standard-issue, cursor is more visible (orange), highlighted region is more visible (light blue)")

(custom-theme-set-faces
 'my-misterioso
 '(cursor ((t (:background "#F88379"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#2e3748"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#338f86" :foreground "#e1e1e0"))))
 ;; '(region ((t (:background "#008B8B" :foreground "#e1e1e0"))))
 '(region ((t (:background "#483d8b"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#fcffad" :foreground "#000000"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#338f86"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#ff4242"))))
 ;; '(mode-line ((((class color) (min-colors 89)) (:background "#212931" :foreground "#eeeeec"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#14191f" :foreground "#eeeeec"))))

 ;; better way to deal with the line-number
 '(line-number ((((class color) (min-colors 257)) (:background "#2e3748" :foreground "#b3b3b3"))))
 '(line-number-current-line ((((class color) (min-colors 257)) (:inherit default :underline nil)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C" :inherit default :underline nil))))
;; end of new line stuff

 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#878787" :foreground "#14191f"))))
 '(header-line ((((class color) (min-colors 89)) (:background "#808080" :foreground "#333333"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#729fcf" :weight bold))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#23d7d7"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#74af68"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#008b8b"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#00ede1" :weight bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#ffad29" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#e67128"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#34cae2"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#dbdb95"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ff4242" :weight bold))))
 '(button ((((class color) (min-colors 89)) (:underline t))))
 '(link ((((class color) (min-colors 89)) (:foreground "#59e9ff" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#ed74cd" :underline t))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:background "#1d2430"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "#1d2430"))))
 '(ediff-even-diff-C ((((class color) (min-colors 89)) (:background "#1d2430"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "#415160"))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:background "#415160"))))
 '(ediff-odd-diff-C ((((class color) (min-colors 89)) (:background "#415160"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:foreground "#ff4242" :weight bold))))
 '(gnus-group-news-1-low ((((class color) (min-colors 89)) (:foreground "#ff4242"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:foreground "#00ede1" :weight bold))))
 '(gnus-group-news-2-low ((((class color) (min-colors 89)) (:foreground "#00ede1"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:foreground "#23d7d7" :weight bold))))
 '(gnus-group-news-3-low ((((class color) (min-colors 89)) (:foreground "#23d7d7"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:foreground "#74af68" :weight bold))))
 '(gnus-group-news-4-low ((((class color) (min-colors 89)) (:foreground "#74af68"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:foreground "#dbdb95" :weight bold))))
 '(gnus-group-news-5-low ((((class color) (min-colors 89)) (:foreground "#dbdb95"))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#008b8b"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:foreground "#ff4242" :weight bold))))
 '(gnus-group-mail-1-low ((((class color) (min-colors 89)) (:foreground "#ff4242"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:foreground "#00ede1" :weight bold))))
 '(gnus-group-mail-2-low ((((class color) (min-colors 89)) (:foreground "#00ede1"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:foreground "#23d7d7" :weight bold))))
 '(gnus-group-mail-3-low ((((class color) (min-colors 89)) (:foreground "#23d7d7"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#008b8b"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:weight normal :foreground "#ffad29"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:foreground "#e67128" :weight bold))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#dbdb95"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#00ede1"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#e67128"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#ffad29" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#e67128"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#e67128"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#dbdb95"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#00ede1"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#74af68"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#23d7d7"))))
 '(ansi-color-black ((((class color) (min-colors 89)) (:background "#2d3743" :foreground "#2d3743"))))
 '(ansi-color-red ((((class color) (min-colors 89)) (:background "#da3938" :foreground "#da3938"))))
 '(ansi-color-green ((((class color) (min-colors 89)) (:background "#74af68" :foreground "#74af68"))))
 '(ansi-color-yellow ((((class color) (min-colors 89)) (:background "#dbdb95" :foreground "#dbdb95"))))
 '(ansi-color-blue ((((class color) (min-colors 89)) (:background "#34cae2" :foreground "#34cae2"))))
 '(ansi-color-magenta ((((class color) (min-colors 89)) (:background "#b33c97" :foreground "#b33c97"))))
 '(ansi-color-cyan ((((class color) (min-colors 89)) (:background "#008b8b" :foreground "#008b8b"))))
 '(ansi-color-white ((((class color) (min-colors 89)) (:background "#e1e1e0" :foreground "#e1e1e0"))))
 '(ansi-color-bright-black ((((class color) (min-colors 89)) (:background "#415160" :foreground "#415160"))))
 '(ansi-color-bright-red ((((class color) (min-colors 89)) (:background "#ff4242" :foreground "#ff4242"))))
 '(ansi-color-bright-green ((((class color) (min-colors 89)) (:background "#74cd65" :foreground "#74cd65"))))
 '(ansi-color-bright-yellow ((((class color) (min-colors 89)) (:background "#ffad29" :foreground "#ffad29"))))
 '(ansi-color-bright-blue ((((class color) (min-colors 89)) (:background "#59e9ff" :foreground "#59e9ff"))))
 '(ansi-color-bright-magenta ((((class color) (min-colors 89)) (:background "#ed74cd" :foreground "#ed74cd"))))
 '(ansi-color-bright-cyan ((((class color) (min-colors 89)) (:background "#00ede1" :foreground "#00ede1"))))
 '(ansi-color-bright-white ((((class color) (min-colors 89)) (:background "#eeeeec" :foreground "#eeeeec"))))
 '(default ((t (:background "#202830" :foreground "#e1e1e0")))))

(provide-theme 'my-misterioso)
