(deftheme my-misterioso
  "Predominantly blue/cyan faces on a dark cyan background. Background is darker than standard-issue, cursor is more visible (orange), highlighted region is more visible (light blue)")

(custom-theme-set-faces
 'my-misterioso
 '(cursor ((t (:background "#F88379"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#2e3748"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#338f86" :foreground "#e1e1e0"))))
 ;; '(region ((t (:background "#008B8B" :foreground "#e1e1e0"))))
 '(region ((t (:background "#483d8b"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#fcffad" :foreground "#000000"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#338f86"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#ff4242"))))
 ;; '(mode-line ((((class color) (min-colors 89)) (:background "#212931" :foreground "#eeeeec"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#14191f" :foreground "#eeeeec"))))

 ;; better way to deal with the line-number
 '(line-number ((((class color) (min-colors 257)) (:background "#2e3748" :foreground "#b3b3b3"))))
 '(line-number-current-line ((((class color) (min-colors 257)) (:inherit default :underline nil)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C" :inherit default :underline nil))))
 ;; end of new line stuff

 ;; trying out a different show-paren-match
 '(show-paren-match ((((class color) (min-colors 257)) (:background "#0471c4" :weight normal))))
 ;; this seems to be a good balance between dark
 ;; (making it readable when I have to highlight the whole expression, as in JSON mode)
 ;; and light (making it visible when highlighting a single delimiter)
 ;;

 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#878787" :foreground "#14191f"))))
 '(header-line ((((class color) (min-colors 89)) (:background "#808080" :foreground "#333333"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#729fcf" :weight bold))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#23d7d7"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#74af68"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#008b8b"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#00ede1" :weight bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#ffad29" :weight bold))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#e67128"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#34cae2"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#dbdb95"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ff4242" :weight bold))))
 '(button ((((class color) (min-colors 89)) (:underline t))))
 '(link ((((class color) (min-colors 89)) (:foreground "#59e9ff" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#ed74cd" :underline t))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:background "#1d2430"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "#1d2430"))))
 '(ediff-even-diff-C ((((class color) (min-colors 89)) (:background "#1d2430"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "#415160"))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:background "#415160"))))
 '(ediff-odd-diff-C ((((class color) (min-colors 89)) (:background "#415160"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:foreground "#ff4242" :weight bold))))
 '(gnus-group-news-1-low ((((class color) (min-colors 89)) (:foreground "#ff4242"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:foreground "#00ede1" :weight bold))))
 '(gnus-group-news-2-low ((((class color) (min-colors 89)) (:foreground "#00ede1"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:foreground "#23d7d7" :weight bold))))
 '(gnus-group-news-3-low ((((class color) (min-colors 89)) (:foreground "#23d7d7"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:foreground "#74af68" :weight bold))))
 '(gnus-group-news-4-low ((((class color) (min-colors 89)) (:foreground "#74af68"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:foreground "#dbdb95" :weight bold))))
 '(gnus-group-news-5-low ((((class color) (min-colors 89)) (:foreground "#dbdb95"))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#008b8b"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:foreground "#ff4242" :weight bold))))
 '(gnus-group-mail-1-low ((((class color) (min-colors 89)) (:foreground "#ff4242"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:foreground "#00ede1" :weight bold))))
 '(gnus-group-mail-2-low ((((class color) (min-colors 89)) (:foreground "#00ede1"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:foreground "#23d7d7" :weight bold))))
 '(gnus-group-mail-3-low ((((class color) (min-colors 89)) (:foreground "#23d7d7"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#008b8b"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:weight normal :foreground "#ffad29"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:foreground "#e67128" :weight bold))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#dbdb95"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#00ede1"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#e67128"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#ffad29" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#e67128"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#e67128"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#dbdb95"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#00ede1"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#74af68"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#23d7d7"))))

 ;; trying out something a little crazy: adding my-monokai's org settings
 '(org-agenda-structure ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#3C3D37" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#202020"))) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#000000" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#1B1E1C")))))
 '(org-agenda-calendar-event ((((class color) (min-colors 257)) (:foreground "#F8F8F0")) (((class color) (min-colors 89)) (:foreground "#FFFAFA"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :slant italic)) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :slant italic))))
 '(org-agenda-date ((((class color) (min-colors 257)) (:foreground "#75715E" :background "#202020" :weight normal :inverse-video nil :overline nil :slant normal :height 1.0 :box (:line-width 2 :color "#202020"))) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C" :weight normal :inverse-video nil :overline nil :slant normal :height 1.0 :box (:line-width 2 :color "#1B1E1C")))))
 '(org-agenda-date-weekend ((((class color) (min-colors 257)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#75715E" :weight unspecified :underline t :overline nil :box unspecified)) (((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#8B8878" :weight unspecified :underline t :overline nil :box unspecified))))
 '(org-agenda-date-today ((((class color) (min-colors 257)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#66D9EF" :background "#202020")) (((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#5FD7FF" :background "#1B1E1C"))))
 '(org-agenda-done ((((class color) (min-colors 257)) (:foreground "#75715E" :slant italic)) (((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(org-archived ((((class color) (min-colors 257)) (:foreground "#75715E" :weight normal)) (((class color) (min-colors 89)) (:foreground "#8B8878" :weight normal))))
 '(org-block ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :background "#3E3D31")) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#3E3E3E"))))
 '(org-block-background ((((class color) (min-colors 257)) (:background "#3E3D31")) (((class color) (min-colors 89)) (:background "#3E3E3E"))))
 '(org-block-begin-line ((((class color) (min-colors 257)) (:foreground "#75715E" :background "#35331D" :slant italic)) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#333333" :slant italic))))
 '(org-block-end-line ((((class color) (min-colors 257)) (:foreground "#75715E" :background "#35331D" :slant italic)) (((class color) (min-colors 89)) (:foreground "#8B8878" :background "#333333" :slant italic))))
 '(org-checkbox ((((class color) (min-colors 257)) (:background "#202020" :foreground "#F8F8F2" :box (:line-width 1 :style released-button))) (((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5" :box (:line-width 1 :style released-button)))))
 '(org-code ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))

 ;; '(org-date ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(org-date ((((class color) (min-colors 257)) (:foreground "#23d7d7" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))

 '(org-done ((((class color) (min-colors 257)) (:weight bold :foreground "#A6E22E")) (((class color) (min-colors 89)) (:weight bold :foreground "#87D700"))))
 '(org-ellipsis ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-formula ((((class color) (min-colors 257)) (:foreground "#E6DB74")) (((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(org-headline-done ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-hide ((((class color) (min-colors 257)) (:foreground "#202020")) (((class color) (min-colors 89)) (:foreground "#1B1E1C"))))
 '(org-level-1 ((((class color) (min-colors 257)) (:inherit default :height 1.3 :foreground "#FD971F")) (((class color) (min-colors 89)) (:inherit default :height 1.3 :foreground "#FF8C00"))))
 '(org-level-2 ((((class color) (min-colors 257)) (:inherit default :height 1.2 :foreground "#A6E22E")) (((class color) (min-colors 89)) (:inherit default :height 1.2 :foreground "#87D700"))))
 '(org-level-3 ((((class color) (min-colors 257)) (:inherit default :height 1.15 :foreground "#66D9EF")) (((class color) (min-colors 89)) (:inherit default :height 1.15 :foreground "#5FD7FF"))))
 '(org-level-4 ((((class color) (min-colors 257)) (:inherit default :height 1.1 :foreground "#E6DB74")) (((class color) (min-colors 89)) (:inherit default :height 1.1 :foreground "#CDC673"))))
 '(org-level-5 ((((class color) (min-colors 257)) (:inherit default :foreground "#A1EFE4")) (((class color) (min-colors 89)) (:inherit default :foreground "#5FFFFF"))))
 '(org-level-6 ((((class color) (min-colors 257)) (:inherit default :foreground "#A6E22E")) (((class color) (min-colors 89)) (:inherit default :foreground "#87D700"))))
 '(org-level-7 ((((class color) (min-colors 257)) (:inherit default :foreground "#F92672")) (((class color) (min-colors 89)) (:inherit default :foreground "#FF1493"))))
 '(org-level-8 ((((class color) (min-colors 257)) (:inherit default :foreground "#66D9EF")) (((class color) (min-colors 89)) (:inherit default :foreground "#5FD7FF"))))

 '(org-link ((((class color) (min-colors 257)) (:foreground "#23d7d7" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 ;; '(org-link ((((class color) (min-colors 257)) (:foreground "#66D9EF" :underline t)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))

 '(org-sexp-date ((((class color) (min-colors 257)) (:foreground "#AE81FF")) (((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(org-scheduled ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-scheduled-previously ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(org-scheduled-today ((((class color) (min-colors 257)) (:foreground "#66D9EF" :weight normal)) (((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight normal))))
 '(org-special-keyword ((((class color) (min-colors 257)) (:foreground "#75715E" :weight bold)) (((class color) (min-colors 89)) (:foreground "#8B8878" :weight bold))))
 '(org-table ((((class color) (min-colors 257)) (:foreground "#A6E22E")) (((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-tag ((((class color) (min-colors 257)) (:weight bold)) (((class color) (min-colors 89)) (:weight bold))))
 '(org-time-grid ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-todo ((((class color) (min-colors 257)) (:foreground "#F92672" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 257)) (:foreground "#E6DB74" :weight normal :underline nil)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal :underline nil))))
 '(org-warning ((((class color) (min-colors 257)) (:foreground "#FD971F" :weight normal :underline nil)) (((class color) (min-colors 89)) (:foreground "#FF8C00" :weight normal :underline nil))))
 '(org-habit-clear-face ((((class color) (min-colors 257)) (:background "#1DB4D0" :foreground "#CAF5FD")) (((class color) (min-colors 89)) (:background "#87D7FF" :foreground "#008787"))))
 '(org-habit-clear-future-face ((((class color) (min-colors 257)) (:background "#1DB4D0")) (((class color) (min-colors 89)) (:background "#87D7FF"))))
 '(org-habit-ready-face ((((class color) (min-colors 257)) (:background "#679A01" :foreground "#A6E22E")) (((class color) (min-colors 89)) (:background "#AFD700" :foreground "#87D700"))))
 '(org-habit-ready-future-face ((((class color) (min-colors 257)) (:background "#679A01")) (((class color) (min-colors 89)) (:background "#AFD700"))))
 '(org-habit-alert-face ((((class color) (min-colors 257)) (:background "#E6DB74" :foreground "#9A8F21")) (((class color) (min-colors 89)) (:background "#CDC673" :foreground "#FFFF87"))))
 '(org-habit-alert-future-face ((((class color) (min-colors 257)) (:background "#9A8F21")) (((class color) (min-colors 89)) (:background "#FFFF87"))))
 '(org-habit-overdue-face ((((class color) (min-colors 257)) (:background "#F92672" :foreground "#F20055")) (((class color) (min-colors 89)) (:background "#FF1493" :foreground "#FF5F87"))))
 '(org-habit-overdue-future-face ((((class color) (min-colors 257)) (:background "#F20055")) (((class color) (min-colors 89)) (:background "#FF5F87"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 257)) (:foreground "#75715E")) (((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 257)) (:background "#E6DB74")) (((class color) (min-colors 89)) (:background "#CDC673"))))
 '(org-clock-overlay ((((class color) (min-colors 257)) (:background "#E6DB74")) (((class color) (min-colors 89)) (:background "#CDC673"))))
 '(org-column ((((class color) (min-colors 257)) (:background "#3C3D37" :strike-through nil :underline nil :slant normal :weight normal :inherit default)) (((class color) (min-colors 89)) (:background "#000000" :strike-through nil :underline nil :slant normal :weight normal :inherit default))))
 '(org-column-title ((((class color) (min-colors 257)) (:background "#3C3D37" :underline t :weight bold)) (((class color) (min-colors 89)) (:background "#000000" :underline t :weight bold))))
 '(org-date-selected ((((class color) (min-colors 257)) (:foreground "#F92672" :inverse-video t)) (((class color) (min-colors 89)) (:foreground "#FF1493" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 257)) (:foreground "#F8F8F2")) (((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(org-document-title ((((class color) (min-colors 257)) (:foreground "#F8F8F0" :weight bold :height 1.3)) (((class color) (min-colors 89)) (:foreground "#FFFAFA" :weight bold :height 1.3))))
 '(org-drawer ((((class color) (min-colors 257)) (:foreground "#A1EFE4")) (((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(org-footnote ((((class color) (min-colors 257)) (:foreground "#FD5FF0" :underline t)) (((class color) (min-colors 89)) (:foreground "#D700D7" :underline t))))
 '(org-latex-and-export-specials ((((class color) (min-colors 257)) (:foreground "#FD971F")) (((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 257)) (:inherit mode-line)) (((class color) (min-colors 89)) (:inherit mode-line))))
 '(outline-1 ((((class color) (min-colors 257)) (:inherit org-level-1)) (((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 257)) (:inherit org-level-2)) (((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 257)) (:inherit org-level-3)) (((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 257)) (:inherit org-level-4)) (((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 257)) (:inherit org-level-5)) (((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 257)) (:inherit org-level-6)) (((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 257)) (:inherit org-level-7)) (((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 257)) (:inherit org-level-8)) (((class color) (min-colors 89)) (:inherit org-level-8))))
 ;; end of addition


 '(ansi-color-black ((((class color) (min-colors 89)) (:background "#2d3743" :foreground "#2d3743"))))
 '(ansi-color-red ((((class color) (min-colors 89)) (:background "#da3938" :foreground "#da3938"))))
 '(ansi-color-green ((((class color) (min-colors 89)) (:background "#74af68" :foreground "#74af68"))))
 '(ansi-color-yellow ((((class color) (min-colors 89)) (:background "#dbdb95" :foreground "#dbdb95"))))
 '(ansi-color-blue ((((class color) (min-colors 89)) (:background "#34cae2" :foreground "#34cae2"))))
 '(ansi-color-magenta ((((class color) (min-colors 89)) (:background "#b33c97" :foreground "#b33c97"))))
 '(ansi-color-cyan ((((class color) (min-colors 89)) (:background "#008b8b" :foreground "#008b8b"))))
 '(ansi-color-white ((((class color) (min-colors 89)) (:background "#e1e1e0" :foreground "#e1e1e0"))))
 '(ansi-color-bright-black ((((class color) (min-colors 89)) (:background "#415160" :foreground "#415160"))))
 '(ansi-color-bright-red ((((class color) (min-colors 89)) (:background "#ff4242" :foreground "#ff4242"))))
 '(ansi-color-bright-green ((((class color) (min-colors 89)) (:background "#74cd65" :foreground "#74cd65"))))
 '(ansi-color-bright-yellow ((((class color) (min-colors 89)) (:background "#ffad29" :foreground "#ffad29"))))
 '(ansi-color-bright-blue ((((class color) (min-colors 89)) (:background "#59e9ff" :foreground "#59e9ff"))))
 '(ansi-color-bright-magenta ((((class color) (min-colors 89)) (:background "#ed74cd" :foreground "#ed74cd"))))
 '(ansi-color-bright-cyan ((((class color) (min-colors 89)) (:background "#00ede1" :foreground "#00ede1"))))
 '(ansi-color-bright-white ((((class color) (min-colors 89)) (:background "#eeeeec" :foreground "#eeeeec"))))
 '(default ((t (:background "#202830" :foreground "#e1e1e0")))))

(provide-theme 'my-misterioso)
